### ISSUE TITLE
when you buy revolver from store animations not appearing

### ISSUE THREAD

**Issue by superstrongbozo** [Piggy3590/PiggysVarietyMod#1]
![image](https://github.com/Piggy3590/PiggysVarietyMod/assets/166734896/59237cad-daeb-4c2d-ba63-33361cb22e90)

**Comment by superstrongbozo** [comment]
not specially from the store

**Comment by Piggy3590** [comment]
fixed in v1.1.12

**Comment by xllifi** [comment]
We got a bug that makes 2 of my friends have animations but me and another friend don't:
<p float="left">
<img src="https://github.com/Piggy3590/PiggysVarietyMod/assets/70767436/dd6542bd-efa6-41e3-a31e-4e6eb5e96379" height=160px />
<img src="https://github.com/Piggy3590/PiggysVarietyMod/assets/70767436/ae523736-8acd-4c10-93be-47016b38b273" height=160px />
<img src="https://github.com/Piggy3590/PiggysVarietyMod/assets/70767436/c95542c0-a157-4915-b639-e4affda58712" height=160px />
<img src="https://github.com/Piggy3590/PiggysVarietyMod/assets/70767436/33522dd1-9cc3-44d3-94d7-a38085073037" height=160px />
<img src="https://github.com/Piggy3590/PiggysVarietyMod/assets/70767436/3ae59e60-8901-4257-bda8-3e5b90087b7c" height=160px />
</p>

Revolver from store, ordered on Gordion
r2modman modpack: `018effdb-b28e-dd66-8961-5e12af042adb`
Full log (names redacted): [LogOutput.txt](https://github.com/Piggy3590/PiggysVarietyMod/files/15051483/LogOutput.txt)

**Comment by Piggy3590** [comment]
> We got a bug that makes 2 of my friends have animations but me and another friend don't:
> 
> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239358-dd6542bd-efa6-41e3-a31e-4e6eb5e96379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzkzNTgtZGQ2NTQyYmQtZWZhNi00MWUzLWEzMWUtNGU2ZWI1ZTk2Mzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMGI5OTAwNTI5ODc2ZTI2MzU1MGExMmYyNjE2YTM5MzkxNzdhODkyODg4NTI2Y2VjZDEzYTlkMTVlOGMxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WjIzY3d07A1lKdurYmaIcNsB2g2lKL_koYbwlSypzvU"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239166-ae523736-8acd-4c10-93be-47016b38b273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzkxNjYtYWU1MjM3MzYtOGFjZC00YzEwLTkzYmUtNDcwMTZiMzhiMjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MzIyNzE5NmEyNDIzYmE4YWRhYjBiNzY5ZDg0Mjg4YWVjNTc3YWY4ZWZiZjY5YWMwYWYyNjhiMjM1MjE1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MvsVmukfRlGkUHWTr2mLunxKXZ646jZkOnBcMTx9xFY"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239199-c95542c0-a157-4915-b639-e4affda58712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzkxOTktYzk1NTQyYzAtYTE1Ny00OTE1LWI2MzktZTRhZmZkYTU4NzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YzJmOGJjM2E4ODExYTQxODNiMzI4M2NjMDU0MTlhZDg5YzZhZWUyMzY0MjA3YTNlYzRiNmExOWE0N2QyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gp1YI_-KxSp0o9fhP9964g-ompIt_5RJgzYmVAJfsZk"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239530-33522dd1-9cc3-44d3-94d7-a38085073037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzk1MzAtMzM1MjJkZDEtOWNjMy00NGQzLTk0ZDctYTM4MDg1MDczMDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOWI2YTIwNjcxZDZlZTMyZjU4N2I2ODRhNmJiMjgwNzdlZTJlYjUyYTg3YzA0ZWNkMzM1YmU3NjkwNTczMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FftQssct69B-Ph6oIfk1hqF9B1zjhpZ-GL7sMeeI6sk"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239438-3ae59e60-8901-4257-bda8-3e5b90087b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzk0MzgtM2FlNTllNjAtODkwMS00MjU3LWJkYTgtM2U1YjkwMDg3YjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NzJiNTRkZDk3ODJmYjMwOWYxZTBjZDNhZjc5YjJmOTc1MGE0ZjhjOWUwNmQyOTc5NWRkMzdlZWZkN2EzYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pjnmkFpHa7oyAshqZzl4K34YS3zBE1yxWW3e3mRLsM">
> 
> Revolver from store, ordered on Gordion r2modman modpack: `018effdb-b28e-dd66-8961-5e12af042adb` Full log (names redacted): [LogOutput.txt](https://github.com/Piggy3590/PiggysVarietyMod/files/15051483/LogOutput.txt)

did your friend say he could see his animations?

**Comment by xllifi** [comment]
> > We got a bug that makes 2 of my friends have animations but me and another friend don't:
> > <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239358-dd6542bd-efa6-41e3-a31e-4e6eb5e96379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzkzNTgtZGQ2NTQyYmQtZWZhNi00MWUzLWEzMWUtNGU2ZWI1ZTk2Mzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMGI5OTAwNTI5ODc2ZTI2MzU1MGExMmYyNjE2YTM5MzkxNzdhODkyODg4NTI2Y2VjZDEzYTlkMTVlOGMxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WjIzY3d07A1lKdurYmaIcNsB2g2lKL_koYbwlSypzvU"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239166-ae523736-8acd-4c10-93be-47016b38b273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzkxNjYtYWU1MjM3MzYtOGFjZC00YzEwLTkzYmUtNDcwMTZiMzhiMjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MzIyNzE5NmEyNDIzYmE4YWRhYjBiNzY5ZDg0Mjg4YWVjNTc3YWY4ZWZiZjY5YWMwYWYyNjhiMjM1MjE1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MvsVmukfRlGkUHWTr2mLunxKXZ646jZkOnBcMTx9xFY"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239199-c95542c0-a157-4915-b639-e4affda58712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzkxOTktYzk1NTQyYzAtYTE1Ny00OTE1LWI2MzktZTRhZmZkYTU4NzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YzJmOGJjM2E4ODExYTQxODNiMzI4M2NjMDU0MTlhZDg5YzZhZWUyMzY0MjA3YTNlYzRiNmExOWE0N2QyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gp1YI_-KxSp0o9fhP9964g-ompIt_5RJgzYmVAJfsZk"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239530-33522dd1-9cc3-44d3-94d7-a38085073037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzk1MzAtMzM1MjJkZDEtOWNjMy00NGQzLTk0ZDctYTM4MDg1MDczMDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOWI2YTIwNjcxZDZlZTMyZjU4N2I2ODRhNmJiMjgwNzdlZTJlYjUyYTg3YzA0ZWNkMzM1YmU3NjkwNTczMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FftQssct69B-Ph6oIfk1hqF9B1zjhpZ-GL7sMeeI6sk"> <img alt="" height="160px" src="https://private-user-images.githubusercontent.com/70767436/324239438-3ae59e60-8901-4257-bda8-3e5b90087b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDg3MDgsIm5iZiI6MTcxMzcwODQwOCwicGF0aCI6Ii83MDc2NzQzNi8zMjQyMzk0MzgtM2FlNTllNjAtODkwMS00MjU3LWJkYTgtM2U1YjkwMDg3YjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NzJiNTRkZDk3ODJmYjMwOWYxZTBjZDNhZjc5YjJmOTc1MGE0ZjhjOWUwNmQyOTc5NWRkMzdlZWZkN2EzYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pjnmkFpHa7oyAshqZzl4K34YS3zBE1yxWW3e3mRLsM">
> > Revolver from store, ordered on Gordion r2modman modpack: `018effdb-b28e-dd66-8961-5e12af042adb` Full log (names redacted): [LogOutput.txt](https://github.com/Piggy3590/PiggysVarietyMod/files/15051483/LogOutput.txt)
> 
> did your friend say he could see his animations?

Yes, he did see animations in FPV
