### ISSUE TITLE
[Request] Config option to adjust tesla gate volume

### ISSUE THREAD

**Issue by ajsglist** [Piggy3590/PiggysVarietyMod#15]
Hi there, we've been using the variety mod for a little while now, and it's really good.

One common concern among our group: the tesla gate sfx are much too loud (at least twice the volume of other ambient effects)

Can we get a config option to set the volume level?

Thanks for the consideration

**Comment by NeatWolf** [comment]
Just came here to make the very same request.
I believe it's objectively too loud.

Being able to configure it would be great!

(Being able to configure other fixed-value parameters, such as the activation radius, frequency, on/off time ratio, damage would be brilliant!)
