### ISSUE TITLE
[Request] Config option to adjust tesla "screen shake" intensity/radius

### ISSUE THREAD

**Issue by NeatWolf** [Piggy3590/PiggysVarietyMod#18]
Hi,

thanks for letting us adjust the audio volume of the tesla!

I'd honestly would like to go as far as asking to expose all possible variables so they can be tweaked, but I understand small requests are more likely to be accepted :P 

When playing with friends we still think the tesla doors are still a bit "over the top":
-There's some bright light 
-There's sound (now configurable, thank you!)
-There's a quite intense screen shake strong enough to cause a jumpscare

Is there any chance to have its intensity and radius tweakable? (when 0, it doesn't create any shake at all)

**Comment by Piggy3590** [comment]
i just updated to 1.1.27, added a config to disable camera shake it bc I couldn't adjust the intensity of the camera shake
