### ISSUE TITLE
More_Emotes incompatibility

### ISSUE THREAD

**Issue by Kondakov02** [Piggy3590/PiggysVarietyMod#20]
https://thunderstore.io/c/lethal-company/p/Sligili/More_Emotes/
When both mods are enabled, prisyadka (emote 9) and sign (emote 10) have strange hands. See the images. Everything related to revolver works fine though.
![20240518164817_1](https://github.com/Piggy3590/PiggysVarietyMod/assets/65817251/bb2e772a-bdd6-4e17-bd28-1eaf13baa69a)
![20240518164819_1](https://github.com/Piggy3590/PiggysVarietyMod/assets/65817251/096f34bd-cca9-4e49-be25-c09f4230a667)
![20240518164825_1](https://github.com/Piggy3590/PiggysVarietyMod/assets/65817251/9c0e213a-3d38-4f8c-a8f8-a6d7ab74032f)

Log file: [MoreEmotes.log](https://github.com/Piggy3590/PiggysVarietyMod/files/15365560/MoreEmotes.log)
Profile code for testing: 018f8c0a-4ef3-3b4a-24d2-470b8ecc1c70

**Comment by Piggy3590** [comment]
this is a technical limitation, I will fix it later if possible.
