### ISSUE TITLE
BetterEmotes incompatibility

### ISSUE THREAD

**Issue by Kondakov02** [Piggy3590/PiggysVarietyMod#21]
Related to #19 
https://thunderstore.io/c/lethal-company/p/KlutzyBubbles/BetterEmotes/
When both mods are enabled, errors are spammed in console related to playerBodyAnimator. Hand animations for revolver also appear to be absent. See the images.
![Lethal Company Screenshot 2024 05 18 - 16 51 38 96](https://github.com/Piggy3590/PiggysVarietyMod/assets/65817251/a197e10b-c8b0-4779-a7d2-6082959a364f)
![Lethal Company Screenshot 2024 05 18 - 16 51 44 61](https://github.com/Piggy3590/PiggysVarietyMod/assets/65817251/e72b447f-647a-4cab-a3a0-c173f9404d05)
![Lethal Company Screenshot 2024 05 18 - 16 51 47 16](https://github.com/Piggy3590/PiggysVarietyMod/assets/65817251/1102c297-63fb-40c0-8fd3-c1b73fb734ef)

Log file: [BetterEmotes.log](https://github.com/Piggy3590/PiggysVarietyMod/files/15365506/BetterEmotes.log)
Profile code for testing: 018f8c06-d41a-969d-46c9-e04f9c6ae198

**Comment by Jawzper** [comment]
Can confirm this issue, would very much appreciate a compatibility fix.
