### ISSUE TITLE
Tesla Gates don't activate?

### ISSUE THREAD

**Issue by Lincolnium** [Piggy3590/PiggysVarietyMod#29]
Been playing with a modpack with this mod in it, and tesla gates have been appearing, but they don't seem to be activating? I remember before v56, they activated normally, and actually were a danger. They seem to be spawning fine, just not actually tesla-ing. Here is the Thunderstore Code: 0190c954-55b3-b1ed-23a0-2365eea9fdda

**Comment by Piggy3590** [comment]
fixed in v1.3.3

**Comment by Lincolnium** [comment]
Appreciate it!
