### ISSUE TITLE
Any chance for the compatablity with more emotes?

### ISSUE THREAD

**Issue by Kablumbaa** [Piggy3590/PiggysVarietyMod#3]
I don't know if it is right place to ask here but is there any chance in the future for the compatability with more emotes?

**Comment by superstrongbozo** [comment]
@Kablumbaa why does he saying that its not compatible? everything is working good for me

**Comment by Kablumbaa** [comment]
@superstrongbozo it says on the mod page that it is incompatible..

**Comment by superstrongbozo** [comment]
@Kablumbaa 
![image](https://github.com/Piggy3590/PiggysVarietyMod/assets/166734896/f4d32a29-d0bc-413e-a751-14ee4c9a4f06)

**Comment by superstrongbozo** [comment]
![Uploading image.png…]()

**Comment by Kablumbaa** [comment]
@superstrongbozo LMAO but why does it says that in the description? Gonna download now xd

**Comment by Kablumbaa** [comment]
![Uploading resim_2024-04-21_023413746.png…]()

**Comment by superstrongbozo** [comment]
@Kablumbaa  
idk bro, try it by your self

**Comment by superstrongbozo** [comment]
![image](https://github.com/Piggy3590/PiggysVarietyMod/assets/166734896/06f7ccb5-f309-44fe-b4f8-e0297d2918c4)

**Comment by Piggy3590** [comment]
its working???

**Comment by Kablumbaa** [comment]
Lol now you updated the mod it doesn't work anymore and many of the games animations are broken.. like pulling ship lever and using terminal.

**Comment by Kablumbaa** [comment]
![image](https://github.com/Piggy3590/PiggysVarietyMod/assets/167421950/d8d68021-f653-4b32-aa0a-28cf6049305e)

@Piggy3590 With the version 1.1.12 it works with more emotes but the playermodel hand animations on the revolver doesn't work.

**Comment by superstrongbozo** [comment]
@Kablumbaa its not more emotes fault, try its ruined because of update

**Comment by Piggy3590** [comment]
> @Kablumbaa its not more emotes fault, try its ruined because of update

they aren't supposed to work together, reason it worked before the update was because a bug prevented player animator from being applied.

**Comment by Piggy3590** [comment]
I'm currently working on compatibility, wait for update :)
