### ISSUE TITLE
[Bug] "Couldn't load assets: Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by ajsglist** [Piggy3590/PiggysVarietyMod#31]
Hey there,

VarietyMod versions post 1.2.1 throw this error on bootup.

![image](https://github.com/user-attachments/assets/89a40014-8618-4a48-91d5-4745a50c220f)

**Comment by ajsglist** [comment]
Howdy,

I sat down to update my mod pack tonight, and the issue persists in 1.3.6

![image](https://github.com/user-attachments/assets/500db40d-a116-456c-b0f9-df3345228f60)

**Comment by Piggy3590** [comment]
You can ignore it.
