### ISSUE TITLE
How to use Korean version?

### ISSUE THREAD

**Issue by pil0lo** [Piggy3590/PiggysVarietyMod#6]
It said in the content that there are instructions for using the Korean version as well.
I don't know exactly what to do.
Source I received the file here and put it in the folder, but it disappeared from the list.

**Comment by Piggy3590** [comment]
set `Enable Korean` to true In the config (Piggy-PiggyVarietyMod.cfg)
그리고 혹시 한국인이시면 한글로 치셔도 돼용

**Comment by pil0lo** [comment]
한국어 쓰시네요.
보통 모드들 제작자 분들 다 영어만 쓰셔서 구글번역 이용했는데요.
store 에서 영어 이름으로 떠서 영어로만 썼는데요.
한국어로 해봐야겠네요.

**Comment by Piggy3590** [comment]
수정중이에용
