### ISSUE TITLE
49버전에서 상점에서 산 리볼버가 작동을 안합니다

### ISSUE THREAD

**Issue by rampa93** [Piggy3590/PiggysVarietyMod#8]
상점에서 산 탄약을 똑같이 상점에서 산 리볼버에 장전하고 쏘려고 하면 격발이 안됩니다.
장전, 실린더 열기, 닫기, 빈총 방아쇠 당기기는 됩니다.
근데 총알 6발 채우고 격발하려고 하면 작동을 안 합니다.
More Emotes 모드를 삭제하고 다시 시도해봤는데 격발이 안됩니다.
49버전에서는 작동을 하지 않는 모드인지 여쭤봅니다.

**Comment by rampa93** [comment]
이미 답변하셨던 내용에 49버전은 지원안한다고 쓰신걸 못 봤습니다 죄송합니다 :((

**Comment by Piggy3590** [comment]
앗 괜찮습니다 제가 따로 적어놔야할 것 같네요
