### ISSUE TITLE
Shotgun and Revolver copying each others animation

### ISSUE THREAD

**Issue by PetiPuss** [Piggy3590/PiggysVarietyMod#9]
![Screenshot 2024-04-24 145857](https://github.com/Piggy3590/PiggysVarietyMod/assets/113295624/7e87cdd1-e1ec-405a-abec-140407139e46)

Hello! It's a bit buggy with the animations when ur holding a shotgun and a revolver. I also noticed that if i put down the shotgun the revolver gets stuck in shotgun animation forever, unless i pick the shotgun again. Sorry for the bad explanation, but most importantly the shotgun and the revolver copies each others animation.

Modpack code for testing: 018f1049-af5e-cefc-11fd-7a3cf881cb4b

**Comment by superstrongbozo** [comment]
this is a lethal company bug i think, sometimes animations bugging also with jetpack and other items with "custom" animation

**Comment by Piggy3590** [comment]
This is a vanilla bug iirc, zeekerss should fix it
